training:
  sde: vesde
  n_iters: 2_000_00
  batch_size: 64
  snapshot_freq: 10000
  log_freq: 10
  eval_freq: 100
  snapshot_freq_for_preemption: 10_000
  snapshot_sampling: False
  epochs: 4

sampling:
  n_steps_each: 1
  noise_removal: True
  probability_flow: False
  snr: 0.17
  method: pc
  predictor: reverse_diffusion
  corrector: langevin
  sampling_abstol: 0.01
  sampling_reltol: 0.01
  sampling_safety: 0.9
  sampling_exp: 0.9
  sampling_h_init: 0.01

data:
  dataset_path: "./datasets/saved_data_pt/train"
  dataset_testpath: "./datasets/saved_data_pt/test"
  min_res_num: 40
  max_res_num: 128
  num_channels: 5
  images_per_epoch: 10

model:
  condition: []
  sigma_max: 100.
  sigma_min: 0.01
  num_scales: 2000
  beta_min: 0.1
  beta_max: 20.
  dropout: 0.1
  embedding_type: positional
  name: ncsnpp
  scale_by_sigma: True
  ema_rate: 0.999
  normalization: GroupNorm
  nonlinearity: swish
  nf: 128
  ch_mult: [1, 1, 2, 2, 2, 2]
  num_res_blocks: 2 
  attn_resolutions: [8, 16, 32, 64, 128]
  resamp_with_conv: True
  skip_rescale: True
  init_self: False  # whether it is the first qk no-tuned
  resblock_type: biggan
  attention_type: ddpm
  weight_scale: 1.
  raw_weight: 8.
  init_scale: 0.
  fourier_scale: 16
  conv_size: 3
  n_heads: 8
  context_dim: 1280 

optim:
  weight_decay: 1.e-2
  optimizer: AdamW
  lr: 1.e-3
  beta1: 0.9
  eps: 1.e-8
  warmup: 5000
  grad_clip: 1.

seed: 42
device: cuda


